development:
  adapter: postgresql
  database: db/development

test:
  adapter: postgresql
  database: db/test

production:
  adapter: postgresql
  database: db/development
  encoding: unicode
  pool: 5
  timeout: 5000
  host: ec2-99-80-200-225.eu-west-1.compute.amazonaws.com
  port: 5432
