development:
  adapter: postgresql
  database: db/development

test:
  adapter: postgresql
  database: db/test

production:
  adapter: postgresql
  database: db/development
  socket: /var/run/postgresql/.s.PGSQL.5432
