development:
  adapter: postgresql
  database: db/development

test:
  adapter: postgresql
  database: db/test

production:
  adapter: postgresql
  database: db/development
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
